### PR TITLE
fix: update tok translation

### PR DESCRIPTION
**Pull request by kilipan**
- updated all tok translation strings to be either full sentences or simple content-phrases.
- left punctuation intact!

hope i've done better this time :)
o awen pona!

### CODE REVIEW

**Comment by anna328p** [comment]
this seems to add periods to a lot of places where they make things ambiguous or inappropriate :(

**Comment by kilipan** [comment]
> this seems to add periods to a lot of places where they make things ambiguous or inappropriate :(

a? how so? can you give some examples, because i'm not sure i understand where you want the periods to be or not to be tbh :sweat_smile:

**Comment by kilipan** [comment]
not sure what exactly the error message tells us here, i don't think there should be any difference to linting

**Comment by anna328p** [comment]
I think Check Run Reporter is just broken.

**Pull request merged**
