### PR TITLE
feat(pt): added pt translation

### PR DESCRIPTION
**Pull request by astindev**

### CODE REVIEW

**Comment by anna328p** [comment]
Please add `pt` to the array [here](https://github.com/arch-community/qbot/blob/4e0331a0ce2809a2db5e165211a683e03ed05f8a/lib/i18n.rb#L6)

**Comment by anna328p** [comment]
also, please use [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) for commit messages (this is the standard the project is following)

**Comment by astindev** [comment]
added!

**Comment by anna328p** [comment]
you changed the name of the pull request, but the commit is still named the same

**Comment by astindev** [comment]
is it possible to change the commit name?

**Comment by Sophon96** [comment]
https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message#amending-older-or-multiple-commit-messages. You'll need to force push.

**Pull request closed without merging**
